exercicio 2
lbsilva8/orion-bootcamp-exercicios pull request #3
Opened 2023-10-13 21:55 UTC by lbsilva8

2023-10-14 00:28 UTC, lbsilva8 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Lorena Borges] Exercicio 2](https://trello.com/c/Wa9nFKPP/36-lorena-borges-exercicio-2)

2023-10-14 15:10 UTC, danielsaviosec requested changes

2023-10-14 15:10 UTC, danielsaviosec commented on src/exercicio2.ts
> +function bioByIdImp(id: number) {
faltou o tipo de retorno da funcao

2023-10-14 15:10 UTC, danielsaviosec commented on src/exercicio2.ts
> +function nameByIdImp(id: number) {
faltou o tipo de retorno da funcao

2023-10-19 00:20 UTC, danielsaviosec approved these changes

2023-10-19 00:21 UTC, merged